package agent

import (
	"context"
	"fmt"
	"testing"
	"time"

	"github.com/marmutapp/openmarmut/internal/config"
	"github.com/marmutapp/openmarmut/internal/llm"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestSpawnSubAgent_TextOnly(t *testing.T) {
	mp := &mockProvider{
		name:  "test",
		model: "test-model",
		responses: []*llm.Response{
			{Content: "Found 3 TODO comments in the codebase.", StopReason: "end",
				Usage: llm.Usage{PromptTokens: 50, CompletionTokens: 20, TotalTokens: 70}},
		},
	}
	rt := newMockRuntime("/project")

	sa, err := SpawnSubAgent(context.Background(), SubAgentOpts{
		Name:     "finder",
		Task:     "Find all TODO comments",
		Provider: mp,
		Runtime:  rt,
		Logger:   testLogger,
	})

	require.NoError(t, err)
	assert.Equal(t, "finder", sa.Name)
	assert.Equal(t, "completed", sa.Status)
	assert.Equal(t, "Found 3 TODO comments in the codebase.", sa.Result)
	assert.Equal(t, 70, sa.Usage.TotalTokens)
	assert.Equal(t, 0, sa.Steps)
	assert.Greater(t, sa.Duration, time.Duration(0))
}

func TestSpawnSubAgent_WithToolCalls(t *testing.T) {
	rt := newMockRuntime("/project")
	rt.files["main.go"] = []byte("package main\n// TODO: implement\n")

	mp := &mockProvider{
		name:  "test",
		model: "test-model",
		responses: []*llm.Response{
			{
				StopReason: "tool_use",
				ToolCalls: []llm.ToolCall{
					{ID: "call_1", Name: "read_file", Arguments: `{"path":"main.go"}`},
				},
			},
			{Content: "Found 1 TODO in main.go", StopReason: "end"},
		},
	}

	sa, err := SpawnSubAgent(context.Background(), SubAgentOpts{
		Task:     "Find TODOs",
		Provider: mp,
		Runtime:  rt,
		Logger:   testLogger,
	})

	require.NoError(t, err)
	assert.Equal(t, "completed", sa.Status)
	assert.Equal(t, "Found 1 TODO in main.go", sa.Result)
	assert.Equal(t, 1, sa.Steps)
}

func TestSpawnSubAgent_AutoGeneratedName(t *testing.T) {
	mp := &mockProvider{
		name:  "test",
		model: "test-model",
		responses: []*llm.Response{
			{Content: "done", StopReason: "end"},
		},
	}
	rt := newMockRuntime("/project")

	sa, err := SpawnSubAgent(context.Background(), SubAgentOpts{
		Task:     "test task",
		Provider: mp,
		Runtime:  rt,
		Logger:   testLogger,
	})

	require.NoError(t, err)
	assert.Contains(t, sa.Name, "sub-")
}

func TestSpawnSubAgent_MaxIterations(t *testing.T) {
	rt := newMockRuntime("/project")
	rt.files["x.txt"] = []byte("x")

	var responses []*llm.Response
	for i := 0; i < 5; i++ {
		responses = append(responses, &llm.Response{
			StopReason: "tool_use",
			ToolCalls: []llm.ToolCall{
				{ID: fmt.Sprintf("call_%d", i), Name: "read_file", Arguments: `{"path":"x.txt"}`},
			},
		})
	}

	mp := &mockProvider{name: "test", model: "m", responses: responses}

	sa, err := SpawnSubAgent(context.Background(), SubAgentOpts{
		Task:     "infinite loop",
		Provider: mp,
		Runtime:  rt,
		Logger:   testLogger,
		MaxIter:  3,
	})

	require.Error(t, err)
	assert.ErrorIs(t, err, ErrMaxIterations)
	assert.Equal(t, "failed", sa.Status)
	assert.Contains(t, sa.Error, "max iterations")
}

func TestSpawnSubAgent_MissingTask(t *testing.T) {
	mp := &mockProvider{name: "test", model: "m"}
	rt := newMockRuntime("/project")

	_, err := SpawnSubAgent(context.Background(), SubAgentOpts{
		Provider: mp,
		Runtime:  rt,
		Logger:   testLogger,
	})

	require.Error(t, err)
	assert.Contains(t, err.Error(), "task is required")
}

func TestSpawnSubAgent_MissingRuntime(t *testing.T) {
	mp := &mockProvider{name: "test", model: "m"}

	_, err := SpawnSubAgent(context.Background(), SubAgentOpts{
		Task:     "test",
		Provider: mp,
		Logger:   testLogger,
	})

	require.Error(t, err)
	assert.Contains(t, err.Error(), "runtime is required")
}

func TestSpawnSubAgent_MissingProvider(t *testing.T) {
	rt := newMockRuntime("/project")

	_, err := SpawnSubAgent(context.Background(), SubAgentOpts{
		Task:    "test",
		Runtime: rt,
		Logger:  testLogger,
	})

	require.Error(t, err)
	assert.Contains(t, err.Error(), "provider is required")
}

func TestSpawnSubAgent_MissingLogger(t *testing.T) {
	mp := &mockProvider{name: "test", model: "m"}
	rt := newMockRuntime("/project")

	_, err := SpawnSubAgent(context.Background(), SubAgentOpts{
		Task:     "test",
		Provider: mp,
		Runtime:  rt,
	})

	require.Error(t, err)
	assert.Contains(t, err.Error(), "logger is required")
}

func TestSpawnSubAgent_IsolatedHistory(t *testing.T) {
	// The parent agent's history should not be polluted by the sub-agent.
	parentProvider := &mockProvider{
		name:  "parent",
		model: "parent-model",
		responses: []*llm.Response{
			{Content: "parent response", StopReason: "end"},
		},
	}
	rt := newMockRuntime("/project")
	parentAgent := New(parentProvider, rt, testLogger)

	// Run parent once.
	_, err := parentAgent.Run(context.Background(), "parent message", nil)
	require.NoError(t, err)
	parentHistoryLen := len(parentAgent.History())

	// Spawn sub-agent.
	subProvider := &mockProvider{
		name:  "sub",
		model: "sub-model",
		responses: []*llm.Response{
			{Content: "sub response", StopReason: "end"},
		},
	}

	sa, err := SpawnSubAgent(context.Background(), SubAgentOpts{
		Task:     "sub task",
		Provider: subProvider,
		Runtime:  rt,
		Logger:   testLogger,
	})
	require.NoError(t, err)
	assert.Equal(t, "sub response", sa.Result)

	// Parent history should be unchanged.
	assert.Len(t, parentAgent.History(), parentHistoryLen)
}

func TestSpawnSubAgent_WithParentContext(t *testing.T) {
	subProvider := &mockProvider{
		name:  "sub",
		model: "sub-model",
		responses: []*llm.Response{
			{Content: "I used the context to complete the task.", StopReason: "end"},
		},
	}
	rt := newMockRuntime("/project")

	parentCtx := []llm.Message{
		{Role: llm.RoleUser, Content: "I'm working on the auth module"},
		{Role: llm.RoleAssistant, Content: "I see the auth module uses JWT."},
	}

	sa, err := SpawnSubAgent(context.Background(), SubAgentOpts{
		Task:      "Check JWT expiry handling",
		Provider:  subProvider,
		Runtime:   rt,
		Logger:    testLogger,
		ParentCtx: parentCtx,
	})

	require.NoError(t, err)
	assert.Equal(t, "completed", sa.Status)

	// The sub-agent's request should include the parent context.
	require.Len(t, subProvider.requests, 1)
	msgs := subProvider.requests[0].Messages
	// Should have: system, parent-context(user), ack(assistant), task(user)
	assert.GreaterOrEqual(t, len(msgs), 4)
	assert.Contains(t, msgs[1].Content, "auth module")
	assert.Contains(t, msgs[2].Content, "context from the parent")
}

func TestSpawnSubAgent_WithConfig(t *testing.T) {
	subProvider := &mockProvider{
		name:  "sub",
		model: "sub-model",
		responses: []*llm.Response{
			{Content: "done", StopReason: "end"},
		},
	}
	rt := newMockRuntime("/project")

	cfg := &config.Config{
		Agent: config.AgentConfig{
			ContextWindow: 64000,
		},
	}

	sa, err := SpawnSubAgent(context.Background(), SubAgentOpts{
		Task:     "check something",
		Provider: subProvider,
		Runtime:  rt,
		Logger:   testLogger,
		Config:   cfg,
	})

	require.NoError(t, err)
	assert.Equal(t, "completed", sa.Status)
}

func TestSpawnSubAgent_CustomSystemPrompt(t *testing.T) {
	subProvider := &mockProvider{
		name:  "sub",
		model: "sub-model",
		responses: []*llm.Response{
			{Content: "custom prompt result", StopReason: "end"},
		},
	}
	rt := newMockRuntime("/project")

	_, err := SpawnSubAgent(context.Background(), SubAgentOpts{
		Task:         "do something",
		Provider:     subProvider,
		Runtime:      rt,
		Logger:       testLogger,
		SystemPrompt: "You are a code reviewer.",
	})

	require.NoError(t, err)
	require.Len(t, subProvider.requests, 1)
	sysMsg := subProvider.requests[0].Messages[0]
	assert.Equal(t, llm.RoleSystem, sysMsg.Role)
	assert.Equal(t, "You are a code reviewer.", sysMsg.Content)
}

func TestSpawnSubAgent_ContextCancellation(t *testing.T) {
	// Create a provider that blocks until context is cancelled.
	mp := &mockProvider{
		name:  "test",
		model: "test-model",
		responses: []*llm.Response{
			// Will not be reached due to cancellation.
		},
	}
	rt := newMockRuntime("/project")

	ctx, cancel := context.WithCancel(context.Background())
	cancel() // Cancel immediately.

	sa, err := SpawnSubAgent(ctx, SubAgentOpts{
		Task:     "should be cancelled",
		Provider: mp,
		Runtime:  rt,
		Logger:   testLogger,
	})

	require.Error(t, err)
	assert.Equal(t, "failed", sa.Status)
}

// --- SubAgentManager Tests ---

func TestSubAgentManager_Track(t *testing.T) {
	mgr := NewSubAgentManager()

	sa := &SubAgent{Name: "test-1", Task: "task 1", Status: "completed"}
	mgr.Track(sa)

	list := mgr.List()
	require.Len(t, list, 1)
	assert.Equal(t, "test-1", list[0].Name)
}

func TestSubAgentManager_TrackDeduplicate(t *testing.T) {
	mgr := NewSubAgentManager()

	sa := &SubAgent{Name: "test-1", Task: "task 1", Status: "completed"}
	mgr.Track(sa)
	mgr.Track(sa) // duplicate

	list := mgr.List()
	assert.Len(t, list, 1)
}

func TestSubAgentManager_Kill(t *testing.T) {
	mgr := NewSubAgentManager()

	// Create a provider that blocks on Complete until context is cancelled.
	started := make(chan struct{})
	blockProvider := &blockingMockProvider{
		name:    "test",
		model:   "test-model",
		started: started,
	}
	rt := newMockRuntime("/project")

	// Use SpawnAsync which registers in running map.
	mgr.SpawnAsync(context.Background(), SubAgentOpts{
		Name:     "blocker",
		Task:     "block forever",
		Provider: blockProvider,
		Runtime:  rt,
		Logger:   testLogger,
	})

	// Wait until the provider's Complete is called.
	<-started

	// Kill it.
	killed := mgr.Kill("blocker")
	assert.True(t, killed)

	// Killing again should return false.
	killed = mgr.Kill("blocker")
	assert.False(t, killed)
}

// blockingMockProvider blocks on Complete until its context is cancelled.
type blockingMockProvider struct {
	name    string
	model   string
	started chan struct{}
}

func (b *blockingMockProvider) Name() string  { return b.name }
func (b *blockingMockProvider) Model() string { return b.model }
func (b *blockingMockProvider) Complete(ctx context.Context, _ llm.Request, _ llm.StreamCallback) (*llm.Response, error) {
	close(b.started)
	<-ctx.Done()
	return nil, ctx.Err()
}

func TestSubAgentManager_KillNonexistent(t *testing.T) {
	mgr := NewSubAgentManager()
	assert.False(t, mgr.Kill("nonexistent"))
}

func TestSubAgentManager_ListEmpty(t *testing.T) {
	mgr := NewSubAgentManager()
	list := mgr.List()
	assert.Empty(t, list)
}

// --- spawn_subagent Tool Tests ---

func TestSpawnSubAgentTool_NotConfigured(t *testing.T) {
	tool := spawnSubAgentTool()
	_, err := tool.Execute(context.Background(), newMockRuntime("/project"), []byte(`{"task":"test"}`))
	require.Error(t, err)
	assert.Contains(t, err.Error(), "not configured")
}

func TestSpawnSubAgentTool_ViaAgent(t *testing.T) {
	// Create a sub-provider that the agent will use for spawning.
	subProvider := &mockProvider{
		name:  "sub",
		model: "sub-model",
		responses: []*llm.Response{
			{Content: "Sub-agent result: 5 files found", StopReason: "end",
				Usage: llm.Usage{TotalTokens: 100}},
		},
	}

	// Main provider calls spawn_subagent, then returns final response.
	mainProvider := &mockProvider{
		name:  "main",
		model: "main-model",
		responses: []*llm.Response{
			{
				StopReason: "tool_use",
				ToolCalls: []llm.ToolCall{
					{ID: "call_1", Name: "spawn_subagent", Arguments: `{"task":"Find all Go files","name":"file-finder"}`},
				},
			},
			{Content: "The sub-agent found 5 files.", StopReason: "end"},
		},
	}

	rt := newMockRuntime("/project")
	ag := New(mainProvider, rt, testLogger,
		WithSubAgentProvider(subProvider, testLogger),
	)

	result, err := ag.Run(context.Background(), "Find all Go files using a sub-agent", nil)

	require.NoError(t, err)
	assert.Equal(t, "The sub-agent found 5 files.", result.Response)
	require.Len(t, result.Steps, 1)
	assert.Contains(t, result.Steps[0].Output, "file-finder")
	assert.Contains(t, result.Steps[0].Output, "completed")
	assert.Contains(t, result.Steps[0].Output, "5 files found")
}

func TestSpawnSubAgentTool_EmptyTask(t *testing.T) {
	subProvider := &mockProvider{
		name:  "sub",
		model: "sub-model",
	}
	mainProvider := &mockProvider{
		name:  "main",
		model: "main-model",
		responses: []*llm.Response{
			{
				StopReason: "tool_use",
				ToolCalls: []llm.ToolCall{
					{ID: "call_1", Name: "spawn_subagent", Arguments: `{"task":""}`},
				},
			},
			{Content: "ok", StopReason: "end"},
		},
	}

	rt := newMockRuntime("/project")
	ag := New(mainProvider, rt, testLogger,
		WithSubAgentProvider(subProvider, testLogger),
	)

	result, err := ag.Run(context.Background(), "test", nil)
	require.NoError(t, err)
	require.Len(t, result.Steps, 1)
	assert.Contains(t, result.Steps[0].Error, "task is required")
}

func TestWithSubAgentProvider_ToolInList(t *testing.T) {
	subProvider := &mockProvider{name: "sub", model: "m"}
	mp := &mockProvider{name: "main", model: "m"}
	rt := newMockRuntime("/project")

	ag := New(mp, rt, testLogger, WithSubAgentProvider(subProvider, testLogger))

	// Verify spawn_subagent is in the tool list.
	found := false
	for _, t := range ag.Tools() {
		if t.Def.Name == "spawn_subagent" {
			found = true
			break
		}
	}
	assert.True(t, found, "spawn_subagent should be in tool list")
}

func TestDefaultPermissions_IncludesSpawnSubagent(t *testing.T) {
	perms := DefaultPermissions()
	level, ok := perms["spawn_subagent"]
	assert.True(t, ok)
	assert.Equal(t, PermConfirm, level)
}
